language: java

dist: focal

jdk:
  - openjdk11
env:
  - ARCH=ppc64le OS=linux

node_js:
  - "12.13"

sudo: required

os: linux

arch: ppc64le

services: docker

script:
  - cat /etc/hostname 
  - cat /etc/resolv.conf
  - cat /etc/os-release
  - sudo apt-get update -y
  - docker pull quay.io/powercloud/powervs-container-host:ocp-latest
  - docker run --rm quay.io/powercloud/powervs-container-host:ocp-latest
  - sudo apt-get install build-essential
