language: c

os: linux

arch:
  - ppc64le
  - amd64

sudo: required

services:
  - docker

script: 
  - uname -a
  - wget https://jcenter.bintray.com/org/ow2/asm/asm/4.1/asm-4.1.pom
  - ping -c google.com
